export const ERROR_CODES = {
  TG_SCAN_INVALID_TOOL_DEFINITION: 'TG_SCAN_INVALID_TOOL_DEFINITION',
  TG_BASELINE_NOT_FOUND: 'TG_BASELINE_NOT_FOUND',
  TG_BASELINE_CORRUPTED: 'TG_BASELINE_CORRUPTED',
  TG_PROJECT_NOT_FOUND: 'TG_PROJECT_NOT_FOUND',
  TG_UNAUTHORIZED: 'TG_UNAUTHORIZED',
  TG_FORBIDDEN: 'TG_FORBIDDEN',
  TG_DRIFT_EVENT_NOT_FOUND: 'TG_DRIFT_EVENT_NOT_FOUND',
  TG_ADAPTER_ERROR: 'TG_ADAPTER_ERROR'
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;

export const RISK_RULE_IDS = {
  CAPABILITY_EXECUTION_ADDED: 'CAPABILITY_EXECUTION_ADDED',
  CAPABILITY_WRITE_ADDED: 'CAPABILITY_WRITE_ADDED',
  CAPABILITY_ADMIN_ADDED: 'CAPABILITY_ADMIN_ADDED',
  CAPABILITY_NETWORK_ADDED: 'CAPABILITY_NETWORK_ADDED',
  ENDPOINT_EXPANDED: 'ENDPOINT_EXPANDED',
  ENDPOINT_CHANGED: 'ENDPOINT_CHANGED',
  AUTH_REQUIREMENT_REMOVED: 'AUTH_REQUIREMENT_REMOVED',
  AUTH_SCOPES_EXPANDED: 'AUTH_SCOPES_EXPANDED',
  SCHEMA_INPUT_EXPANDED: 'SCHEMA_INPUT_EXPANDED',
  SCHEMA_INPUT_MODIFIED: 'SCHEMA_INPUT_MODIFIED',
  DESCRIPTION_CHANGED: 'DESCRIPTION_CHANGED',
  VERSION_CHANGED: 'VERSION_CHANGED',
  PROPERTY_REMOVED: 'PROPERTY_REMOVED',
  GENERIC_MODIFICATION: 'GENERIC_MODIFICATION'
} as const;

export type RiskRuleId = keyof typeof RISK_RULE_IDS;

export const DEFAULT_PATHS = {
  CONFIG_FILE: '.toolguard/config.json',
  BASELINE_FILE: '.toolguard/baseline.json',
  TOOLS_DIR: '.toolguard/tools'
} as const;
